package cn.kanmars.sn.entity;

public class TblSysuserRoleInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sysuser_role_info.user_no
     *
     * @mbggenerated Thu Jan 07 22:42:51 CST 2016
     */
    private String userNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sysuser_role_info.role_no
     *
     * @mbggenerated Thu Jan 07 22:42:51 CST 2016
     */
    private String roleNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sysuser_role_info
     *
     * @mbggenerated Thu Jan 07 22:42:51 CST 2016
     */
    public TblSysuserRoleInfoKey(String userNo, String roleNo) {
        this.userNo = userNo;
        this.roleNo = roleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sysuser_role_info
     *
     * @mbggenerated Thu Jan 07 22:42:51 CST 2016
     */
    public TblSysuserRoleInfoKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sysuser_role_info.user_no
     *
     * @return the value of tbl_sysuser_role_info.user_no
     *
     * @mbggenerated Thu Jan 07 22:42:51 CST 2016
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sysuser_role_info.user_no
     *
     * @param userNo the value for tbl_sysuser_role_info.user_no
     *
     * @mbggenerated Thu Jan 07 22:42:51 CST 2016
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sysuser_role_info.role_no
     *
     * @return the value of tbl_sysuser_role_info.role_no
     *
     * @mbggenerated Thu Jan 07 22:42:51 CST 2016
     */
    public String getRoleNo() {
        return roleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sysuser_role_info.role_no
     *
     * @param roleNo the value for tbl_sysuser_role_info.role_no
     *
     * @mbggenerated Thu Jan 07 22:42:51 CST 2016
     */
    public void setRoleNo(String roleNo) {
        this.roleNo = roleNo;
    }
}