package cn.kanmars.sn.entity;


public class TblSysroleMenuInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sysrole_menu_info.role_no
     *
     * @mbggenerated Thu Jan 07 22:42:51 CST 2016
     */
    private String roleNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sysrole_menu_info.menu_no
     *
     * @mbggenerated Thu Jan 07 22:42:51 CST 2016
     */
    private String menuNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sysrole_menu_info
     *
     * @mbggenerated Thu Jan 07 22:42:51 CST 2016
     */
    public TblSysroleMenuInfoKey(String roleNo, String menuNo) {
        this.roleNo = roleNo;
        this.menuNo = menuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sysrole_menu_info
     *
     * @mbggenerated Thu Jan 07 22:42:51 CST 2016
     */
    public TblSysroleMenuInfoKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sysrole_menu_info.role_no
     *
     * @return the value of tbl_sysrole_menu_info.role_no
     *
     * @mbggenerated Thu Jan 07 22:42:51 CST 2016
     */
    public String getRoleNo() {
        return roleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sysrole_menu_info.role_no
     *
     * @param roleNo the value for tbl_sysrole_menu_info.role_no
     *
     * @mbggenerated Thu Jan 07 22:42:51 CST 2016
     */
    public void setRoleNo(String roleNo) {
        this.roleNo = roleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sysrole_menu_info.menu_no
     *
     * @return the value of tbl_sysrole_menu_info.menu_no
     *
     * @mbggenerated Thu Jan 07 22:42:51 CST 2016
     */
    public String getMenuNo() {
        return menuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sysrole_menu_info.menu_no
     *
     * @param menuNo the value for tbl_sysrole_menu_info.menu_no
     *
     * @mbggenerated Thu Jan 07 22:42:51 CST 2016
     */
    public void setMenuNo(String menuNo) {
        this.menuNo = menuNo;
    }
}